// Code generated by protoc-gen-go.
// source: chunk.proto
// DO NOT EDIT!

package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChunkLoc struct {
	MapName string `protobuf:"bytes,1,opt,name=mapName" json:"mapName,omitempty"`
	X       int32  `protobuf:"varint,2,opt,name=x" json:"x,omitempty"`
	Y       int32  `protobuf:"varint,3,opt,name=y" json:"y,omitempty"`
}

func (m *ChunkLoc) Reset()                    { *m = ChunkLoc{} }
func (m *ChunkLoc) String() string            { return proto.CompactTextString(m) }
func (*ChunkLoc) ProtoMessage()               {}
func (*ChunkLoc) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ChunkLoc) GetMapName() string {
	if m != nil {
		return m.MapName
	}
	return ""
}

func (m *ChunkLoc) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ChunkLoc) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type IntRow struct {
	Items []int32 `protobuf:"varint,1,rep,packed,name=items" json:"items,omitempty"`
}

func (m *IntRow) Reset()                    { *m = IntRow{} }
func (m *IntRow) String() string            { return proto.CompactTextString(m) }
func (*IntRow) ProtoMessage()               {}
func (*IntRow) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *IntRow) GetItems() []int32 {
	if m != nil {
		return m.Items
	}
	return nil
}

type FloatRow struct {
	Items []float32 `protobuf:"fixed32,1,rep,packed,name=items" json:"items,omitempty"`
}

func (m *FloatRow) Reset()                    { *m = FloatRow{} }
func (m *FloatRow) String() string            { return proto.CompactTextString(m) }
func (*FloatRow) ProtoMessage()               {}
func (*FloatRow) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *FloatRow) GetItems() []float32 {
	if m != nil {
		return m.Items
	}
	return nil
}

type Unit struct {
	Uuid     string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	TileHash string `protobuf:"bytes,2,opt,name=tileHash" json:"tileHash,omitempty"`
}

func (m *Unit) Reset()                    { *m = Unit{} }
func (m *Unit) String() string            { return proto.CompactTextString(m) }
func (*Unit) ProtoMessage()               {}
func (*Unit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Unit) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Unit) GetTileHash() string {
	if m != nil {
		return m.TileHash
	}
	return ""
}

type Chunk struct {
	Hash      string      `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Map       string      `protobuf:"bytes,2,opt,name=map" json:"map,omitempty"`
	X         int32       `protobuf:"varint,3,opt,name=x" json:"x,omitempty"`
	Y         int32       `protobuf:"varint,4,opt,name=y" json:"y,omitempty"`
	NavGrid   []*IntRow   `protobuf:"bytes,5,rep,name=navGrid" json:"navGrid,omitempty"`
	Grid      []*FloatRow `protobuf:"bytes,6,rep,name=grid" json:"grid,omitempty"`
	ChunkSize int32       `protobuf:"varint,7,opt,name=chunkSize" json:"chunkSize,omitempty"`
	Units     []*Unit     `protobuf:"bytes,8,rep,name=units" json:"units,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Chunk) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Chunk) GetMap() string {
	if m != nil {
		return m.Map
	}
	return ""
}

func (m *Chunk) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Chunk) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Chunk) GetNavGrid() []*IntRow {
	if m != nil {
		return m.NavGrid
	}
	return nil
}

func (m *Chunk) GetGrid() []*FloatRow {
	if m != nil {
		return m.Grid
	}
	return nil
}

func (m *Chunk) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *Chunk) GetUnits() []*Unit {
	if m != nil {
		return m.Units
	}
	return nil
}

func init() {
	proto.RegisterType((*ChunkLoc)(nil), "services.ChunkLoc")
	proto.RegisterType((*IntRow)(nil), "services.IntRow")
	proto.RegisterType((*FloatRow)(nil), "services.FloatRow")
	proto.RegisterType((*Unit)(nil), "services.Unit")
	proto.RegisterType((*Chunk)(nil), "services.Chunk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Map service

type MapClient interface {
	GetChunk(ctx context.Context, in *ChunkLoc, opts ...grpc.CallOption) (*Chunk, error)
}

type mapClient struct {
	cc *grpc.ClientConn
}

func NewMapClient(cc *grpc.ClientConn) MapClient {
	return &mapClient{cc}
}

func (c *mapClient) GetChunk(ctx context.Context, in *ChunkLoc, opts ...grpc.CallOption) (*Chunk, error) {
	out := new(Chunk)
	err := grpc.Invoke(ctx, "/services.Map/getChunk", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Map service

type MapServer interface {
	GetChunk(context.Context, *ChunkLoc) (*Chunk, error)
}

func RegisterMapServer(s *grpc.Server, srv MapServer) {
	s.RegisterService(&_Map_serviceDesc, srv)
}

func _Map_GetChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkLoc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MapServer).GetChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Map/GetChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MapServer).GetChunk(ctx, req.(*ChunkLoc))
	}
	return interceptor(ctx, in, info, handler)
}

var _Map_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Map",
	HandlerType: (*MapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getChunk",
			Handler:    _Map_GetChunk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chunk.proto",
}

func init() { proto.RegisterFile("chunk.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x91, 0xdd, 0x4a, 0x33, 0x31,
	0x10, 0x86, 0xbf, 0x74, 0x37, 0x6d, 0x3a, 0xfd, 0xd0, 0x32, 0x78, 0x10, 0x8a, 0xc8, 0xb2, 0x88,
	0x2c, 0x1e, 0x14, 0xac, 0x20, 0x1e, 0x0a, 0x82, 0x3f, 0xa0, 0x1e, 0x44, 0xbc, 0x80, 0xd8, 0x86,
	0x36, 0xd8, 0xfd, 0x61, 0x37, 0x5b, 0x5b, 0xef, 0xd6, 0x3b, 0x91, 0x64, 0x37, 0x2e, 0xea, 0xd9,
	0xbc, 0x99, 0x67, 0x32, 0xf3, 0xce, 0xc0, 0x68, 0xbe, 0xaa, 0xb3, 0xb7, 0x69, 0x51, 0xe6, 0x26,
	0x47, 0x56, 0xa9, 0x72, 0xa3, 0xe7, 0xaa, 0x8a, 0xaf, 0x80, 0x5d, 0xdb, 0xc4, 0x43, 0x3e, 0x47,
	0x0e, 0x83, 0x54, 0x16, 0x4f, 0x32, 0x55, 0x9c, 0x44, 0x24, 0x19, 0x0a, 0x2f, 0xf1, 0x3f, 0x90,
	0x2d, 0xef, 0x45, 0x24, 0xa1, 0x82, 0x6c, 0xad, 0xda, 0xf1, 0xa0, 0x51, 0xbb, 0xf8, 0x08, 0xfa,
	0xf7, 0x99, 0x11, 0xf9, 0x3b, 0x1e, 0x00, 0xd5, 0x46, 0xa5, 0x15, 0x27, 0x51, 0x90, 0x50, 0xd1,
	0x88, 0x38, 0x02, 0x76, 0xb3, 0xce, 0xe5, 0x5f, 0xa2, 0xe7, 0x89, 0x0b, 0x08, 0x5f, 0x32, 0x6d,
	0x10, 0x21, 0xac, 0x6b, 0xbd, 0x68, 0x9b, 0xbb, 0x18, 0x27, 0xc0, 0x8c, 0x5e, 0xab, 0x3b, 0x59,
	0xad, 0xdc, 0x00, 0x43, 0xf1, 0xad, 0xe3, 0x4f, 0x02, 0xd4, 0x0d, 0x6f, 0x2b, 0x57, 0x96, 0x68,
	0x2b, 0x6d, 0x8c, 0x63, 0x08, 0x52, 0x59, 0xb4, 0x45, 0x36, 0x6c, 0x5c, 0x04, 0x3f, 0x5c, 0x84,
	0xad, 0x0b, 0x3c, 0x85, 0x41, 0x26, 0x37, 0xb7, 0xa5, 0x5e, 0x70, 0x1a, 0x05, 0xc9, 0x68, 0x36,
	0x9e, 0xfa, 0x1d, 0x4d, 0x1b, 0x7b, 0xc2, 0x03, 0x78, 0x02, 0xe1, 0xd2, 0x82, 0x7d, 0x07, 0x62,
	0x07, 0x7a, 0x9f, 0xc2, 0xe5, 0xf1, 0x10, 0x86, 0x6e, 0xe9, 0xcf, 0xfa, 0x43, 0xf1, 0x81, 0xeb,
	0xd4, 0x3d, 0xe0, 0x31, 0xd0, 0x3a, 0xd3, 0xa6, 0xe2, 0xcc, 0x7d, 0xb3, 0xd7, 0x7d, 0x63, 0x97,
	0x21, 0x9a, 0xe4, 0xec, 0x12, 0x82, 0x47, 0x59, 0xe0, 0x19, 0xb0, 0xa5, 0x32, 0xad, 0xd9, 0x8e,
	0xf4, 0xa7, 0x9b, 0xec, 0xff, 0x7a, 0x8b, 0xff, 0xbd, 0xf6, 0xdd, 0xa9, 0xcf, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x32, 0xef, 0x52, 0xf9, 0x01, 0x00, 0x00,
}
