
before_script:
  - docker info

stages:
  - build
  - test
  - deploy

standalone_build:
  stage: build
  script:
    - docker-compose -f docker-compose-standalone.yml build

standalone_test:
  stage: test
  script:
    - docker-compose -f docker-compose-standalone.yml up

prod_deploy:
  stage: deploy
  script:
    - echo 'Not Implemented'