image: docker/compose:1.22.0

before_script:
  - docker info

# Cache modules in between jobs
# not actually used because node_modules is in container...
# cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#  - node_modules/

stages:
  - build
  - test
  - deploy

standalone_build:
  stage: build
  script:
    - docker-compose build

standalone_test:
  stage: test
  script:
    - docker-compose up rethink
    - docker-compose run standalone yarn test
    - docker-compose stop rethink

prod_deploy:
  stage: deploy
  script:
    - echo 'Not Implemented'