// Generated by CoffeeScript 1.4.0
(function() {
  var Ready, WorldGenerator, db, init, waitForDB;

  db = require('./db.js');

  WorldGenerator = require('./worldGenerator.js');

  waitForDB = function() {
    if (!db.Ready) {
      setTimeout(init, 1);
      return false;
    } else {
      return true;
    }
  };

  init = function() {
    var badMars;
    if (waitForDB()) {
      badMars = WorldGenerator.generate();
      return console.log('Server Ready');
    }
  };

  Ready = false;

  db.init();

  console.log('DB Loaded');

  WorldGenerator.init();

  console.log('World Generator Loaded');

  init();

}).call(this);
