version: '2'
services:
  simulate:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/simulate/simulate.go
    volumes:
      - ./bin:/badmars/bin
      - ./server:/go/src/github.com/monofuel/badmars/server
    links:
#      - rethinkdb
      - ai
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/dashboard/dashboard.go
    volumes:
      - ./bin:/badmars/bin
      - ./server:/go/src/github.com/monofuel/badmars/server
      - ./public:/go/src/github.com/monofuel/badmars/public
#    links:
#      - rethinkdb
    ports:
      - '8090:8090'
    environment:
      - BADMARS_DB=rethinkdb.mono
  chunk:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor chunk.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
#    links:
#      - rethinkdb
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono
  ai:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor ai.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
    links:
#      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono
  pathfinder:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor pathfinder.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
    links:
#      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono
  validator:
    build: .
    command: sh -c 'cd bin/server/nodejs && node validator.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
    links:
#      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono
  web:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor web.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
      - ./client:/badmars/client
      - ./public:/badmars/public
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_WS_SERVER=ws://192.168.11.119
      - BADMARS_DB=rethinkdb.mono
    ports:
      - "3002:3002"
#    links:
#      - rethinkdb
  client:
    build: .
    command: make watchClient
    volumes:
      - ./server:/badmars/server
      - ./client:/badmars/client
      - ./public:/badmars/public
    ports:
      - "4474:4474"
#    links:
#      - rethinkdb
    environment:
      - BADMARS_DB=rethinkdb.mono
  dashboard-frontend:
    build: .
    command: make watchDashboard
    volumes:
      - ./client:/badmars/client
      - ./public:/badmars/public
#    links:
#      - rethinkdb
    environment:
      - BADMARS_DB=rethinkdb.mono
  net:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor net.js'
    volumes:
      - ./bin:/badmars/bin
      - ./server:/badmars/server
    ports:
      - "7005:7005"
      - "5858:5858"
#    links:
#      - rethinkdb
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethinkdb.mono