version: '2'
services:
  simulate:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/simulate/simulate.go
    volumes:
      - ./:/go/src/github.com/monofuel/badmars
    links:
      - rethink
      - ai
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/dashboard/dashboard.go
    volumes:
      - ./:/go/src/github.com/monofuel/badmars
    links:
      - rethink
    ports:
      - '8090:8090'
    environment:
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  chunk:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor chunk.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    links:
      - rethink
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
  ai:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor ai.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    links:
      - rethink
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  pathfinder:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor pathfinder.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    links:
      - rethink
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  validator:
    build: .
    command: sh -c 'cd bin/server/nodejs && node validator.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    links:
      - rethink
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  web:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor web.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_WS_SERVER=ws://localhost
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    ports:
      - "3002:3002"
    links:
      - rethink
    depends_on:
      - schema
  client:
    build: .
    command: sh -c 'make watchClient'
    volumes:
      - ./:/badmars
    ports:
      - "4474:4474"
    links:
      - rethink
    environment:
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
  dashboard-frontend:
    build: .
    command: sh -c 'make watchDashboard'
    volumes:
      - ./:/badmars
    links:
      - rethink
    environment:
      - BADMARS_DB=rethink
    depends_on:
      - schema
  net:
    build: .
    command: sh -c 'cd bin/server/nodejs && supervisor net.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    ports:
      - "7005:7005"
      - "5858:5858"
    links:
      - rethink
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net
    depends_on:
      - schema
  rethink:
    image: rethinkdb
    ports:
      - "8085:8080"
    volumes:
      - rethink_data:/data
  schema:
    build: .
    command: sh -c 'cd bin/server/nodejs && node schema.js'
    volumes:
      - ./:/badmars
      - /badmars/node_modules
    links:
      - rethink
    environment:
      - BADMARS_DB=rethink
      - TRACKING_SERVER=http://japura.net


volumes:
  rethink_data:
    driver: local
