version: '2'
services:
  standalone:
    build:
      context: .
      dockerfile: Dockerfile-go-node
    command: make run
    volumes:
      - ./bin/data/:/go/src/github.com/monofuel/badmars/bin/data
  proxy:
    build:
      context: ./nginx
    volumes:
      - ./nginx/standalone_nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    links:
      - standalone

  rethink:
    image: rethinkdb
    ports:
      - "8085:8080"
      - "28015:28015"
    volumes:
      - rethink_data:/data

volumes:
  rethink_data:
    driver: local