version: '2'
services:
  simulate:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/simulate/simulate.go
    volumes:
      - ./server:/go/src/github.com/monofuel/badmars/server
    links:
      - rethinkdb
      - ai
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run server/go/core/dashboard/dashboard.go
    volumes:
      - ./server:/go/src/github.com/monofuel/badmars/server
    links:
      - rethinkdb
    ports:
      - '8090:8090'
  chunk:
    build: .
    command: bash -c 'cd server/nodejs && supervisor chunk.js'
    volumes:
      - ./server:/badmars/server
    links:
      - rethinkdb
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  ai:
    build: .
    command: bash -c 'cd server/nodejs && supervisor ai.js'
    volumes:
      - ./server:/badmars/server
    links:
      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  pathfinder:
    build: .
    command: bash -c 'cd server/nodejs && supervisor pathfinder.js'
    volumes:
      - ./server:/badmars/server
    links:
      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  validator:
    build: .
    command: bash -c 'cd server/nodejs && supervisor -n validator.js'
    volumes:
      - ./server:/badmars/server
    links:
      - rethinkdb
      - chunk
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  web:
    build: .
    command: bash -c 'cd server/nodejs && supervisor web.js & make watchClient'
    volumes:
      - ./server:/badmars/server
      - ./client:/badmars/client
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
      - BADMARS_WS_SERVER=ws://192.168.11.119
    ports:
      - "3002:3002"
    links:
      - rethinkdb
  net:
    build: .
    command: bash -c 'cd server/nodejs && supervisor net.js'
    volumes:
      - ./server:/badmars/server
    ports:
      - "7005:7005"
    links:
      - rethinkdb
    environment:
      - MAP_HOST=chunk
      - AI_HOST=ai
  rethinkdb:
    image: rethinkdb
    ports:
      - "8085:8080"
