version: '2'
services:
  standalone:
    build:
      context: .
    command: make run
    # TODO user id breaks CI
    volumes:
      - ./bin:/badmars/bin
      # - ./bin/data/:/go/src/github.com/monofuel/badmars/bin/data
    ports:
      - '3002:3002'
      - '7005:7005'
    environment:
      - INFLUX_SERVER=influx:8086
  chrono:
    image: chronograf
    ports:
      - '8888:8888'
    command: chronograf --influxdb-url=http://influx:8086
  influx:
    image: influxdb
    ports:
      - "8086:8086"
  rethink:
    image: rethinkdb
    ports:
      - "8085:8080"
      - "28015:28015"
    # TODO user id breaks CI
    #volumes:
    #  - rethink_data:/data

volumes:
  rethink_data:
    driver: local