// Generated by CoffeeScript 1.9.3
var World, mongoose;

mongoose = require('mongoose');

World = mongoose.model('World');

module.exports = function(app) {
  return app.route('/worlds').get(function(req, res, next) {
    console.log(req.query);
    if (req.query.name === void 0) {
      World.find(function(err, worlds) {
        var i, len, world, worldNames;
        if (err) {
          console.log(err);
          return next(err);
        }
        worldNames = new Array();
        for (i = 0, len = worlds.length; i < len; i++) {
          world = worlds[i];
          worldNames.push(world.name);
        }
        return res.json({
          worlds: worldNames
        });
      });
      return;
    }
    return World.find({
      name: req.query.name
    }, function(err, world) {
      if (err) {
        console.log(err);
        return next(err);
      }
      res.json(world);
    });
  });
};
