apiVersion: v1
kind: Service
metadata:
 labels:
   name: ai
 name: ai
spec:
 ports:
   - port: 3010
     targetPort: 3010
 selector:
   name: ai
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ai-deployment
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    kind: Deployment
    name: ai-deployment
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ai-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ai
    spec:
      containers:
      - image: king.mono:5000/badmars-1242/badmars_node:v$VERSION
        name: ai
        command: ["sh"]
        args: ["-c", "cd bin/server/nodejs && node ai.js"]
        resources:
          requests:
            cpu: 30m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: ai
          containerPort: 3010
          hostPort: 3010
        env:
        - name: BADMARS_DB
          value: "rethinkdb.mono"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: BADMARS_WS_SERVER
          value: "wss://japura.net"
        - name: BADMARS_WS_PUBLIC_PORT
          value: "7006"
        - name: TRACKING_SERVER
          value: "http://andrelytics.mono"