apiVersion: v1
kind: Service
metadata:
 labels:
   name: auth
 name: auth
spec:
 ports:
   - name: auth
     port: 3004
 selector:
   name: auth
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-deployment
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: auth-deployment
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
      - image: localhost:5000/badmars_go:v$VERSION
        name: auth
        command: ["go"]
        args: ["run", "server/go/core/auth/main.go"]
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
        env:
        - name: BADMARS_DB
          value: rethinkdb