apiVersion: v1
kind: Service
metadata:
 labels:
   name: chunk
 name: chunk
spec:
 ports:
   - name: chunk
     port: 3011
 selector:
   name: chunk
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chunk-deployment
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deployment
    name: chunk-deployment
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chunk-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: chunk
    spec:
      containers:
      - image: localhost:5000/badmars_node:v$VERSION
        name: chunk
        command: ["sh"]
        args: ["-c", "cd bin/server/nodejs && node chunk.js"]
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: chunk
          containerPort: 3011
        env:
        - name: NODE_ENV
          value: "prod"
        - name: BADMARS_DB
          value: "rethinkdb"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: TRACKING_SERVER
          value: "http://andrelytics.mono"