apiVersion: v1
kind: Service
metadata:
 labels:
   name: net
 name: net
spec:
 ports:
   - name: web
     port: 7005
     targetPort: 7005
   - name: hotreload
     port: 5858
     targetPort: 5858
 selector:
   name: net
---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: net-deployment
  namespace: default
spec:
  cpuUtilization:
    targetPercentage: 80
  maxReplicas: 3
  minReplicas: 1
  scaleRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: net-deployment
    subresource: scale
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: net-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: net
    spec:
      containers:
      - image: gcr.io/badmars-1242/badmars_node:v$VERSION
        name: net
        command: ["sh"]
        args: ["-c", "cd server/nodejs && babel-watch net.js"]
        resources:
          requests:
            cpu: 20m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: net
          containerPort: 7005
          hostPort: 7005
        - name: hotreload
          containerPort: 5858
          hostPort: 5858
        env:
        - name: BADMARS_DB
          value: "10.128.0.5"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: TRACKING_SERVER
          value: "http://japura.net"