apiVersion: v1
kind: Service
metadata:
 labels:
   name: net
 name: net
spec:
 type: NodePort
 selector:
  name: net
 ports:
   - name: net
     port: 7005
 selector:
   name: net
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: net-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: net
    spec:
      containers:
      - image: localhost:5000/badmars_node:v$VERSION
        name: net
        command: ["sh"]
        args: ["-c", "cd bin/server/nodejs && node net.js"]
        resources:
          requests:
            cpu: 20m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: net
          containerPort: 7005
        env:
        - name: NODE_ENV
          value: "prod"
        - name: BADMARS_DB
          value: "rethinkdb"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: TRACKING_SERVER
          value: "http://andrelytics.mono"