apiVersion: v1
kind: Service
metadata:
 labels:
   name: nginx
 name: nginx
spec:
 type: NodePort
 selector:
  name: nginx
 ports:
   - name: nginx
     port: 80
 selector:
   name: net
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: net
    spec:
      containers:
      - image: localhost:5000/badmars_proxy:v$VERSION
        name: proxy
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
        ports:
        - name: proxy
          containerPort: 80