apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simulate-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: simulate
    spec:
      containers:
      - image: localhost:5000/badmars_go:v$VERSION
        name: simulate
        command: ["go"]
        args: ["run", "server/go/core/simulate/simulate.go"]
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
        env:
        - name: BADMARS_DB
          value: "rethinkdb"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: TRACKING_SERVER
          value: "http://andrelytics.mono"