apiVersion: v1
kind: Service
metadata:
 labels:
   name: web
 name: web
spec:
 ports:
   - port: 3002
     targetPort: 3002
 selector:
   name: web
---
apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: web-deployment
  namespace: default
spec:
  cpuUtilization:
    targetPercentage: 80
  maxReplicas: 1
  minReplicas: 1
  scaleRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: web-deployment
    subresource: scale
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/badmars-1242/badmars_node:v$VERSION
        name: web
        command: ["sh"]
        args: ["-c", "cd server/nodejs && babel-watch web.js"]
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
        livenessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /_health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: web
          containerPort: 3002
          hostPort: 3002
        env:
        - name: BADMARS_DB
          value: "10.128.0.5"
        - name: MAP_HOST
          value: "chunk"
        - name: AI_HOST
          value: "ai"
        - name: BADMARS_WS_SERVER
          value: "ws://104.197.75.241"
        - name: TRACKING_SERVER
          value: "http://japura.net"