FROM node:argon

RUN npm install -g flow browserify

WORKDIR /root/

RUN echo "deb http://download.rethinkdb.com/apt `lsb_release -cs` main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
RUN wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
RUN apt-get update
RUN apt-get install rethinkdb

RUN mkdir -p /go/src/github.com/monofuel
ENV gopath /go

RUN wget https://storage.googleapis.com/golang/go1.7.1.linux-amd64.tar.gz

RUN tar -xvf go1.7.1.linux-amd64.tar.gz

ENV GOBIN /root/go
RUN export PATH=$PATH:/root/go/bin

RUN go version

EXPOSE 3002
EXPOSE 7005
