
apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-admin
spec:
  ports:
   - port: 8080
     nodePort: 31080
  type: NodePort
  selector:
    db: rethinkdb
    role: admin
