apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb-proxy
spec:
  replicas: 1
  selector:
    db: rethinkdb
    role: proxy
  template:
    metadata:
      labels:
        db: rethinkdb
        role: proxy
    spec:
      containers:
      - image: rosskukulinski/rethinkdb-kubernetes:2.2.5
        imagePullPolicy: Always
        name: rethinkdb
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        env:
        - name: PROXY
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RETHINK_CLUSTER
          value: rethinkdb-cluster
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data/rethinkdb_data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        emptyDir: {}
